# JVM toolchain
kotlinVersion=2.3.21
micronautVersion=5.1.3
micronautDataVersion=5.0.0
hibernateVersion=6.6.2.Final
postgresDriverVersion=42.7.4
flywayVersion=10.20.1

# Test stack
junitVersion=5.11.3
mockkVersion=1.13.13
kotestVersion=5.9.1
testcontainersVersion=1.20.3

# Gradle runtime
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureOnDemand=true
kotlin.daemon.jvmargs=-Xmx1g
kotlin.incremental=true
